# Generated by Django 5.0.7 on 2024-07-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndRegistartionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
